tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/mssql-release"
brew "libffi"
brew "sqlite"
brew "python@3.9"
brew "cairo"
brew "gdk-pixbuf"
brew "openjdk"
brew "gradle"
brew "hstr"
brew "libpq", link: true
brew "pango"
brew "microsoft/mssql-release/msodbcsql17", link: false
brew "microsoft/mssql-release/mssql-tools"
